### ISSUE TITLE
Find Transfermarket Data

### ISSUE THREAD

**Issue by lukas-hager** [lukas-hager/csss566-epl#4]
Thanks Alejandro

**Comment by AleO19** [comment]
I found the transfermarket data per team for the seasons we needed. I tried to use some kaggle data, but it was not really useful. I ended up copying it in a spreadsheet (that is in the drive). The only issue is that we only have data per team and not per player.

**Comment by lukas-hager** [comment]
Got it -- thanks for doing that! I'll take a look this afternoon. Appreciate it, Alejandro!

**Comment by lukas-hager** [comment]
Data in the drive looks good to me -- I don't think it's too much of a problem that it's by team (it will certainly make the merge easier). Let me know if I'm missing something obvious and I can reopen the issue!
